export const plStrings = {
  extensionName:"Report a bug",
  bugsToRetestTabName: "Bugs to retest and close",
  allBugsTabName: "All bugs reported by me",
  cornerDialogDismissButtonText: "Dismiss",
  submitBugButtonText: "Submit a bug",
  submitBugButtonTooltip: "Open bug report form",
  bugIdColumnName: "Id",
  bugTitleColumnName: "Title",
  bugCreatedByColumName: "Created By",
  bugStateColumnName: "State",
  bugReasonColumnName: "Reason",
  bugModifiedDateColumnName: "Last modified date",
  ariaLabelAscending: "Sorted A to Z",
  ariaLabelDescending: "Sorted Z to A",
  ariaLabelAscendingNumeric: "Sorted low to high",
  ariaLabelDescendingNumeric: "Sorted high to low",
  bugReportFormName: "Bug report from",
  bugReportFormDescription: "To report a bug or issue, please fill below form and click Create button.",
  bugTitleErrorMessage: "Bug title cannot be empty",
  bugDescriptionErrorMessage: "Description cannot be empty",
  reproStepsErorrMessage: "Repro steps cannot be empty",
  severityErorrMessage: "Choose severity",
  createBugButtonText: "Create",
  cancelCreateBugButtonText: "Cancel",
  bugTitleFieldLabel: "Bug Title",
  bugIdFieldLabel: "Id",
  bugTitleFieldPlaceholder: "Enter Bug Title",
  bugDescriptionFieldLabel: "Bug description",
  bugDescriptionFieldPlaceholder: "Enter bug description",
  bugReproFieldLabel: "Repro steps",
  bugReporFieldPlacehodler: "Describe steps to reproduce the bug",
  bugSeverityFieldLabel: "Bug severity",
  bugSeverityFieldPlaceholder: "Choose severity",
  bugStateFiledLabel: "Bug state",
  bugReasonFiledLabel: "Reason",
  bugCommentFieldLabel: "Comments",
  bugCreatedDateFieldLabel:"Created",
  bugCreatedByFieldLabel:"Created by",
  bugModifiedDateFieldLabel: "Modified",
  bugModifiedByFieldLabel:"Modified by",
  reportBugSuccessDialogTitle: "Report a bug",
  reportBugSuccessDialogMessage: "Bug submitted sucessfully",
  rejectReasonDialogFieldLablel: "Please enter a reject reason",
  rejectReasonErrorMessage: "Reject reason cannot be empty",
  rejectReasonDialogFieldPlaceholder: "Describe reject reason",
  viewBugFormTitle: "Resolve/Reject Bug",
  viewBugFormDescription: "To resolve a bug or issue, please click Resolve button. To resolve a bug or issue, please click Reject button.",
  viewBugFormCancelButtonText: "Cancel",
  viewBugFormCloseButtonText: "Close",
  viewBugFormRejectButtonText: "Reject",
  bugDetailsLinkLabel: "Clik here for bug details",
  bugTestCaseLinkLabel: "Clik here for associated test case",
  rejectDialogRejectButtonText: "Reject",
  rejectDialogCancelButtonText: "Cancel",
  rejectConfirmDialogTitle: "Report a bug",
  rejectConfirmDialogMessage: "Bug rejected",
  closeConfirmDialogTitle: "Report a bug",
  closeConfirmDialogMessage: "Bug closed",
  dateTimeFormatString: "dd.MM.yyyy HH:mm:ss"
}