import { plStrings } from './plStrings';
import { enStrings } from './enStrings';
import LocalizedStrings, { LocalizedStringsMethods } from 'react-localization';

export interface LocaleStrings extends LocalizedStringsMethods {
    extensionName: string,
    bugsToRetestTabName: string,
    allBugsTabName: string,
    cornerDialogDismissButtonText: string,
    submitBugButtonText: string,
    submitBugButtonTooltip: string,
    bugIdColumnName: string,
    bugTitleColumnName: string,
    bugCreatedByColumName: string,
    bugStateColumnName: string,
    bugReasonColumnName: string,
    bugModifiedDateColumnName: string,
    ariaLabelAscending: string,
    ariaLabelDescending: string,
    ariaLabelAscendingNumeric: string,
    ariaLabelDescendingNumeric: string,
    bugReportFormName: string,
    bugReportFormDescription: string,
    bugTitleErrorMessage: string,
    bugDescriptionErrorMessage: string,
    reproStepsErorrMessage: string,
    severityErorrMessage: string,
    createBugButtonText: string,
    cancelCreateBugButtonText: string,
    bugIdFieldLabel: string,
    bugTitleFieldLabel: string,
    bugTitleFieldPlaceholder: string,
    bugDescriptionFieldLabel: string,
    bugDescriptionFieldPlaceholder: string,
    bugReproFieldLabel: string,
    bugReporFieldPlacehodler: string,
    bugSeverityFieldLabel: string,
    bugSeverityFieldPlaceholder: string,
    bugStateFiledLabel: string,
    bugReasonFiledLabel: string,
    bugCommentFieldLabel: string,
    bugCreatedDateFieldLabel:string,
    bugCreatedByFieldLabel:string,
    bugModifiedDateFieldLabel: string,
    bugModifiedByFieldLabel:string,
    reportBugSuccessDialogTitle: string,
    reportBugSuccessDialogMessage: string,
    rejectReasonErrorMessage: string,
    rejectReasonDialogFieldLablel: string,
    rejectReasonDialogFieldPlaceholder: string,
    viewBugFormTitle: string,
    viewBugFormDescription: string,
    viewBugFormCancelButtonText: string,
    viewBugFormCloseButtonText: string,
    viewBugFormRejectButtonText: string,
    bugDetailsLinkLabel: string,
    bugTestCaseLinkLabel: string,
    rejectDialogRejectButtonText: string,
    rejectDialogCancelButtonText: string,
    rejectConfirmDialogTitle: string,
    rejectConfirmDialogMessage: string,
    closeConfirmDialogTitle: string,
    closeConfirmDialogMessage: string,
    dateTimeFormatString: string
}

export const LocalizationStrings: LocaleStrings = new LocalizedStrings({
    pl: plStrings,
    en: enStrings
});